[package]
name = "T-Reader"
version = "0.4.0"
description = "An ePub Reader based on Tauri"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "t_reader_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.1", features = [] }

[dependencies]
tauri = { version = "2.0.4", features = [] }
tauri-plugin-shell = "2.0.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-fs = "2"
dirs = "4.0"
tauri-plugin-dialog = "2"
tauri-plugin-http = "2"
reqwest = {version = "0.11", default-features = false, features = ["rustls-tls", "stream"] }
http = "0.2"
tauri-plugin-os = "2"
quick-xml = "0.22"
futures-util = "0.3"
fontdb = "0.23"
tauri-plugin-updater = "2.10.0"
tauri-plugin-process = "2.3.1"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-window-state = "2"

