/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIcon: typeof import('./src/components/common/AppIcon/index.vue')['default']
    BookInfoDialog: typeof import('./src/components/BookInfoDialog/index.vue')['default']
    BookMarkDialog: typeof import('./src/components/BookMark/bookMarkDialog.vue')['default']
    BookMarkTag: typeof import('./src/components/BookMark/bookMarkTag.vue')['default']
    BookMetadataEditDialog: typeof import('./src/components/BookMetadataEditDialog.vue')['default']
    BubbleToggle: typeof import('./src/components/common/BubbleToggle/index.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu/index.vue')['default']
    DrawDialog: typeof import('./src/components/DrawDialog/index.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    GenerationStatusBar: typeof import('./src/components/DrawDialog/GenerationStatusBar.vue')['default']
    HelpDialog: typeof import('./src/components/HelpDialog/index.vue')['default']
    LoadingBlockade: typeof import('./src/components/common/LoadingBlockade/index.vue')['default']
    ModelProviderForm: typeof import('./src/components/SettingDialog/ModelProviderForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StyleMenu: typeof import('./src/components/StyleMenu/index.vue')['default']
    SystemFontEnableDialog: typeof import('./src/components/SystemFontEnableDialog/index.vue')['default']
    TocMenu: typeof import('./src/components/TocMenu/index.vue')['default']
  }
}
