/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BookMark: typeof import('./src/components/BookMark.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu/index.vue')['default']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    Greet: typeof import('./src/components/Greet.vue')['default']
    LoadingBlockade: typeof import('./src/components/loadingBlockade.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    MenuComponent: typeof import('./src/components/MenuComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
