// 系统自带的阅读不常用字体
export const fontExclusion = [  
  "Bahnschrift",  
  "Bookman Old Style",
  "Bookshelf Symbol 7",
  "Bradley Hand ITC",
  "Calibri",
  "Cambria",
  "Cambria Math", 
  "Candara", 
  "Cascadia Code",  
  "Cascadia Mono",  
  "Century", 
  "Century Gothic",
  "Comic Sans MS",
  "Consolas",
  "Constantia",
  "Corbel",
  "Courier New",  
  "DengXian",  
  "Dubai",  
  "Ebrima",  
  "Franklin Gothic Medium",  
  "Freestyle Script",  
  "French Script MT",  
  "Gabriola",  
  "Gadugi",
  "Garamond", 
  "Georgia", 
  "Haettenschweiler",  
  "Microsoft Himalaya",  
  "Impact",  
  "Ink Free",  
  "Kristen ITC",  
  "Javanese Text",  
  "Juice ITC",  
  "Leelawadee",  
  "Leelawadee UI",  
  "Lucida Console",
  "Lucida Handwriting", 
  "Lucida Sans Unicode", 
  "Marlett",  
  "Microsoft Sans Serif",  
  "Mistral",  
  "Myanmar Text",  
  "Mongolian Baiti",  
  "MS Gothic",  
  "MS PGothic",  
  "MS UI Gothic",  
  "Microsoft Uighur",  
  "Microsoft Yi Baiti",  
  "Monotype Corsiva", 
  "MS Outlook", 
  "MT Extra",  
  "MV Boli",  
  "Nirmala UI",  
  "Nirmala Text",  
  "Noto Sans SC",
  "Noto Serif SC",
  "Malgun Gothic",
  "Microsoft New Tai Lue",  
  "Microsoft Tai Le",  
  "Microsoft PhagsPa", 
  "MingLiU-ExtB",
  "MingLiU_HKSCS-ExtB",
  "MingLiU_MSCS-ExtB",
  "MS Reference Sans Serif",  
  "MS Reference Specialty",  
  "Palatino Linotype",
  "PMingLiU-ExtB",
  "Sans Serif Collection",
  "Segoe MDL2 Assets",  
  "Segoe Fluent Icons",  
  "Segoe Print",  
  "Segoe Script",  
  "Segoe UI",
  "Segoe UI Emoji",  
  "Segoe UI Historic",  
  "Segoe UI Symbol",  
  "Segoe UI Variable",
  "SimSun-ExtB",  
  "SimSun-ExtG",  
  "Sitka",  
  "Source Han Serif SC",
  "STCaiyun",  
  "STFangsong",  
  "STHupo",  
  "STKaiti",  
  "STLiti",  
  "STSong",  
  "STXihei",  
  "STXingkai",  
  "STXinwei",  
  "STZhongsong",  
  "Sylfaen",  
  "Symbol",  
  "Tahoma",
  "Tempus Sans ITC",  
  "Trebuchet MS",
  "Verdana",
  "Webdings",  
  "Wingdings",  
  "Wingdings 2",  
  "Wingdings 3",  
  "Yu Gothic",  
  "Yu Gothic UI"  
]