// 系统自带的阅读不常用字体
export const fontExclusion = [ 
  "Agency FB",
  "Algerian",
  "Arial",
  "Arial Rounded MT Bold",
  "Bahnschrift",
  "Baskerville Old Face",
  "Bauhaus 93",
  "Bell MT",
  "Berlin Sans FB",
  "Berlin Sans FB Demi",
  "Bernard MT Condensed",
  "Blackadder ITC",
  "Bodoni MT",
  "Book Antiqua",
  "Bookman Old Style",
  "Bookshelf Symbol 7",
  "Bradley Hand ITC",
  "Britannic Bold",
  "Broadway",
  "Brush Script MT",
  "Calibri",
  "Calisto MT",
  "Californian FB",
  "Cambria",
  "Cambria Math",
  "Candara",
  "Cascadia Code",
  "Cascadia Mono",
  "Castellar",
  "Centaur",
  "Century",
  "Century Gothic",
  "Century Schoolbook",
  "Chiller",
  "Colonna MT",
  "Comic Sans MS",
  "Consolas",
  "Constantia",
  "Cooper Black",
  "Copperplate Gothic Bold",
  "Copperplate Gothic Light",
  "Corbel",
  "Courier New",
  "Curlz MT",
  "DejaVu Sans Mono",
  "DengXian",
  "DIN Next LT Pro",
  "Dubai",
  "Ebrima",
  "Edwardian Script ITC",
  "Elephant",
  "Engravers MT",
  "Eras Bold ITC",
  "Eras Demi ITC",
  "Eras Light ITC",
  "Eras Medium ITC",
  "Felix Titling",
  "Fences",
  "Footlight MT Light",
  "Forte",
  "Franklin Gothic Book",
  "Franklin Gothic Demi",
  "Franklin Gothic Demi Cond",
  "Franklin Gothic Heavy",
  "Franklin Gothic Medium",
  "Franklin Gothic Medium Cond",
  "Freestyle Script",
  "French Script MT",
  "Gabriola",
  "Gadugi",
  "Garamond",
  "Georgia",
  "Gigi",
  "Gill Sans MT",
  "Gill Sans MT Condensed",
  "Gill Sans MT Ext Condensed Bold",
  "Gill Sans Ultra Bold",
  "Gill Sans Ultra Bold Condensed",
  "Gloucester MT Extra Condensed",
  "Goudy Old Style",
  "Goudy Stout",
  "Haettenschweiler",
  "Harlow Solid Italic",
  "Harrington",
  "High Tower Text",
  "HoloLens MDL2 Assets",
  "Impact",
  "Imprint MT Shadow",
  "Ink Free",
  "Informal Roman",
  "Javanese Text",
  "JetBrains Mono",
  "JetBrains Mono NL",
  "Jokerman",
  "Juice ITC",
  "Kunstler Script",
  "Kristen ITC",
  "Leelawadee",
  "Leelawadee UI",
  "Lucida Bright",
  "Lucida Calligraphy",
  "Lucida Console",
  "Lucida Fax",
  "Lucida Handwriting",
  "Lucida Sans",
  "Lucida Sans Typewriter",
  "Lucida Sans Unicode",
  "Magneto",
  "Maiandra GD",
  "Malgun Gothic",
  "Marlett",
  "Matura MT Script Capitals",
  "Microsoft Himalaya",
  "Microsoft New Tai Lue",
  "Microsoft PhagsPa",
  "Microsoft Sans Serif",
  "Microsoft Tai Le",
  "Microsoft Uighur",
  "Microsoft Yi Baiti",
  "MingLiU-ExtB",
  "MingLiU_HKSCS-ExtB",
  "MingLiU_MSCS-ExtB",
  "Modern No. 20",
  "Mongolian Baiti",
  "Monotype Corsiva",
  "MS Gothic",
  "MS Outlook",
  "MS PGothic",
  "MS Reference Sans Serif",
  "MS Reference Specialty",
  "MS UI Gothic",
  "MT Extra",
  "MV Boli",
  "Myanmar Text",
  "Niagara Engraved",
  "Niagara Solid",
  "Nirmala Text",
  "Nirmala UI",
  "Noto Sans SC",
  "Noto Serif SC",
  "NumberOnly",
  "OCR A Extended",
  "Old English Text MT",
  "Onyx",
  "Origin",
  "PMingLiU-ExtB",
  "Palace Script MT",
  "Palatino Linotype",
  "Papyrus",
  "Parchment",
  "Perpetua",
  "Perpetua Titling MT",
  "Playbill",
  "Poor Richard",
  "Pristina",
  "Rage Italic",
  "Ravie",
  "Rockwell",
  "Rockwell Condensed",
  "Rockwell Extra Bold",
  "Sans Serif Collection",
  "Script MT Bold",
  "Segoe Fluent Icons",
  "Segoe MDL2 Assets",
  "Segoe Print",
  "Segoe Script",
  "Segoe UI",
  "Segoe UI Emoji",
  "Segoe UI Historic",
  "Segoe UI Symbol",
  "Segoe UI Variable",
  "Showcard Gothic",
  "SimSun-ExtB",
  "SimSun-ExtG",
  "Sitka",
  "Snap ITC",
  "sshlinedraw",
  "Source Han Serif SC",
  "STCaiyun",
  "STFangsong",
  "STHupo",
  "STKaiti",
  "STLiti",
  "STSong",
  "STXihei",
  "STXingkai",
  "STXinwei",
  "STZhongsong",
  "Stencil",
  "Sylfaen",
  "Symbol",
  "Tahoma",
  "Tempus Sans ITC",
  "Times New Roman",
  "Trebuchet MS",
  "Tw Cen MT",
  "Tw Cen MT Condensed",
  "Tw Cen MT Condensed Extra Bold",
  "Unispace",
  "Verdana",
  "Viner Hand ITC",
  "Vivaldi",
  "Vladimir Script",
  "Webdings",
  "Wide Latin",
  "Wingdings",
  "Wingdings 2",
  "Wingdings 3",
  "Yu Gothic",
  "Yu Gothic UI"
]