name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-latest
            args: ''
            target: 'x86_64-pc-windows-msvc'
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install frontend dependencies
        run: |
          npm ci
          cd libs/epub.js
          npm ci

      - name: Read Release Notes
        id: read_release_notes
        shell: bash
        run: |
          if [ -f RELEASE_NOTES.md ]; then
            EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
            echo "notes<<$EOF" >> $GITHUB_OUTPUT
            cat RELEASE_NOTES.md >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "$EOF" >> $GITHUB_OUTPUT
          else
            echo "notes=Update ${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          fi

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'T-Reader ${{ github.ref_name }}'
          releaseBody: ${{ steps.read_release_notes.outputs.notes }}
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
